package com.wcg.caoxian.bes.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.wcg.caoxian.bes.model.MstObject;
import com.wcg.caoxian.bes.vo.mastervo.ObjectExcelVo;
import com.wcg.caoxian.bes.vo.mastervo.ObjectSearchOutVo;
import com.wcg.caoxian.sdk.bean.PageBean;

public interface MstObjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_object
     *
     * @mbg.generated Thu Dec 14 13:42:42 CST 2017
     */
    int deleteByPrimaryKey(String code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_object
     *
     * @mbg.generated Thu Dec 14 13:42:42 CST 2017
     */
    int insert(MstObject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_object
     *
     * @mbg.generated Thu Dec 14 13:42:42 CST 2017
     */
    int insertSelective(MstObject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_object
     *
     * @mbg.generated Thu Dec 14 13:42:42 CST 2017
     */
    MstObject selectByPrimaryKey(String code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_object
     *
     * @mbg.generated Thu Dec 14 13:42:42 CST 2017
     */
    int updateByPrimaryKeySelective(MstObject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_object
     *
     * @mbg.generated Thu Dec 14 13:42:42 CST 2017
     */
    int updateByPrimaryKey(MstObject record);

    /**
     * @Title: searchByCondition
     * @Description: 根据查询条件获取数据对象列表
     * @author 李洋  liyang
     * @data 2017年12月14日 下午1:51:52
     * @return List<ObjectSearchOutVo>
     */
	List<ObjectSearchOutVo> searchByCondition(@Param("keyword")String keyword, @Param("page")PageBean pageBean);

	/**
	 * @Title: searchCount
	 * @Description: 根据查询条件获取数据对象列表记录数
	 * @author 李洋  liyang
	 * @data 2017年12月14日 下午1:57:47
	 * @return long
	 */
	long searchCount(@Param("keyword")String keyword);

	/**
	 * @Title: selectByCode
	 * @Description: 根据主键获取数据对象列表信息
	 * @author 李洋  liyang
	 * @data 2018年6月19日 上午11:30:31
	 * @return List<ObjectExcelVo>
	 */
	List<ObjectExcelVo> selectByCode(@Param("code")String[] objectCodes);
}