package com.wcg.caoxian.bes.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.wcg.caoxian.bes.model.RolePermission;

public interface RolePermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ur_role_permission
     *
     * @mbg.generated Fri Sep 22 13:40:32 CST 2017
     */
    int insert(RolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ur_role_permission
     *
     * @mbg.generated Fri Sep 22 13:40:32 CST 2017
     */
    int insertSelective(RolePermission record);

    /**
     * @Title: searchRolePermissionCount
     * @Description: 查询改权限菜单是否被角色引用
     * @author 李洋  liyang
     * @data 2017年10月10日 下午2:23:31
     * @return int
     */
	int searchRolePermissionCount(@Param(value="permissionCd")String code);

	/**
	 * @Title: deleteByRoleCd
	 * @Description: 根绝角色编码删除角色-权限 关系
	 * @author 李洋  liyang
	 * @data 2017年10月11日 上午10:11:05
	 * @return int
	 */
	int deleteByRoleCd(@Param(value="roleCd")String code);
	
	/**
	 * @Title: searchPerCdsByRoleCd
	 * @Description: 根据角色编码获取权限菜单编码列表
	 * @author 李洋  liyang
	 * @data 2017年10月11日 上午10:50:33
	 * @return List<String>
	 */
	List<String> searchPerCdsByRoleCd(@Param(value="roleCd")String code);
}