package com.wcg.caoxian.bes.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.wcg.caoxian.bes.model.UserRole;

public interface UserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ur_user_role
     *
     * @mbg.generated Fri Sep 22 13:40:32 CST 2017
     */
    int insert(UserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ur_user_role
     *
     * @mbg.generated Fri Sep 22 13:40:32 CST 2017
     */
    int insertSelective(UserRole record);

    /**
     * @Title: searchUserRoleCount
     * @Description: 查询角色是否被用户引用
     * @author 李洋  liyang
     * @data 2017年10月11日 下午1:33:50
     * @return int
     */
	int searchUserRoleCount(@Param(value="roleCd")String code);
	
	/**
	 * @Title: searchRoleCdsByUserCd
	 * @Description: 根据用户编码获取用户-角色编码列表
	 * @author 李洋  liyang
	 * @data 2017年10月11日 下午2:20:28
	 * @return List<String>
	 */
	List<String> searchRoleCdsByUserCd(@Param(value="userCd")String code);

	/**
	 * @Title: deleteByUserCd
	 * @Description: 根据用户编码删除用户-角色关系
	 * @author 李洋  liyang
	 * @data 2017年10月11日 下午4:25:59
	 * @return int
	 */
	int deleteByUserCd(@Param(value="userCd")String code);
	
}