package com.wcg.caoxian.bes.model;

import java.util.Date;

public class User {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ur_user.code
	 * @mbg.generated  Fri Sep 29 10:14:24 CST 2017
	 */
	private String code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ur_user.name
	 * @mbg.generated  Fri Sep 29 10:14:24 CST 2017
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ur_user.login_name
	 * @mbg.generated  Fri Sep 29 10:14:24 CST 2017
	 */
	private String loginName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ur_user.mobile
	 * @mbg.generated  Fri Sep 29 10:14:24 CST 2017
	 */
	private String mobile;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ur_user.password
	 * @mbg.generated  Fri Sep 29 10:14:24 CST 2017
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ur_user.init_flag
	 * @mbg.generated  Fri Sep 29 10:14:24 CST 2017
	 */
	private Boolean initFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ur_user.version_no
	 * @mbg.generated  Fri Sep 29 10:14:24 CST 2017
	 */
	private Integer versionNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ur_user.created_time
	 * @mbg.generated  Fri Sep 29 10:14:24 CST 2017
	 */
	private Date createdTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ur_user.created_by_cd
	 * @mbg.generated  Fri Sep 29 10:14:24 CST 2017
	 */
	private String createdByCd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ur_user.last_updated_time
	 * @mbg.generated  Fri Sep 29 10:14:24 CST 2017
	 */
	private Date lastUpdatedTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ur_user.last_updated_by_cd
	 * @mbg.generated  Fri Sep 29 10:14:24 CST 2017
	 */
	private String lastUpdatedByCd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ur_user.deleted_flag
	 * @mbg.generated  Fri Sep 29 10:14:24 CST 2017
	 */
	private Boolean deletedFlag;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ur_user.code
	 * @return  the value of ur_user.code
	 * @mbg.generated  Fri Sep 29 10:14:24 CST 2017
	 */
	public String getCode() {
		return code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ur_user.code
	 * @param code  the value for ur_user.code
	 * @mbg.generated  Fri Sep 29 10:14:24 CST 2017
	 */
	public void setCode(String code) {
		this.code = code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ur_user.name
	 * @return  the value of ur_user.name
	 * @mbg.generated  Fri Sep 29 10:14:24 CST 2017
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ur_user.name
	 * @param name  the value for ur_user.name
	 * @mbg.generated  Fri Sep 29 10:14:24 CST 2017
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ur_user.login_name
	 * @return  the value of ur_user.login_name
	 * @mbg.generated  Fri Sep 29 10:14:24 CST 2017
	 */
	public String getLoginName() {
		return loginName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ur_user.login_name
	 * @param loginName  the value for ur_user.login_name
	 * @mbg.generated  Fri Sep 29 10:14:24 CST 2017
	 */
	public void setLoginName(String loginName) {
		this.loginName = loginName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ur_user.mobile
	 * @return  the value of ur_user.mobile
	 * @mbg.generated  Fri Sep 29 10:14:24 CST 2017
	 */
	public String getMobile() {
		return mobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ur_user.mobile
	 * @param mobile  the value for ur_user.mobile
	 * @mbg.generated  Fri Sep 29 10:14:24 CST 2017
	 */
	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ur_user.password
	 * @return  the value of ur_user.password
	 * @mbg.generated  Fri Sep 29 10:14:24 CST 2017
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ur_user.password
	 * @param password  the value for ur_user.password
	 * @mbg.generated  Fri Sep 29 10:14:24 CST 2017
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ur_user.init_flag
	 * @return  the value of ur_user.init_flag
	 * @mbg.generated  Fri Sep 29 10:14:24 CST 2017
	 */
	public Boolean getInitFlag() {
		return initFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ur_user.init_flag
	 * @param initFlag  the value for ur_user.init_flag
	 * @mbg.generated  Fri Sep 29 10:14:24 CST 2017
	 */
	public void setInitFlag(Boolean initFlag) {
		this.initFlag = initFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ur_user.version_no
	 * @return  the value of ur_user.version_no
	 * @mbg.generated  Fri Sep 29 10:14:24 CST 2017
	 */
	public Integer getVersionNo() {
		return versionNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ur_user.version_no
	 * @param versionNo  the value for ur_user.version_no
	 * @mbg.generated  Fri Sep 29 10:14:24 CST 2017
	 */
	public void setVersionNo(Integer versionNo) {
		this.versionNo = versionNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ur_user.created_time
	 * @return  the value of ur_user.created_time
	 * @mbg.generated  Fri Sep 29 10:14:24 CST 2017
	 */
	public Date getCreatedTime() {
		return createdTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ur_user.created_time
	 * @param createdTime  the value for ur_user.created_time
	 * @mbg.generated  Fri Sep 29 10:14:24 CST 2017
	 */
	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ur_user.created_by_cd
	 * @return  the value of ur_user.created_by_cd
	 * @mbg.generated  Fri Sep 29 10:14:24 CST 2017
	 */
	public String getCreatedByCd() {
		return createdByCd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ur_user.created_by_cd
	 * @param createdByCd  the value for ur_user.created_by_cd
	 * @mbg.generated  Fri Sep 29 10:14:24 CST 2017
	 */
	public void setCreatedByCd(String createdByCd) {
		this.createdByCd = createdByCd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ur_user.last_updated_time
	 * @return  the value of ur_user.last_updated_time
	 * @mbg.generated  Fri Sep 29 10:14:24 CST 2017
	 */
	public Date getLastUpdatedTime() {
		return lastUpdatedTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ur_user.last_updated_time
	 * @param lastUpdatedTime  the value for ur_user.last_updated_time
	 * @mbg.generated  Fri Sep 29 10:14:24 CST 2017
	 */
	public void setLastUpdatedTime(Date lastUpdatedTime) {
		this.lastUpdatedTime = lastUpdatedTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ur_user.last_updated_by_cd
	 * @return  the value of ur_user.last_updated_by_cd
	 * @mbg.generated  Fri Sep 29 10:14:24 CST 2017
	 */
	public String getLastUpdatedByCd() {
		return lastUpdatedByCd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ur_user.last_updated_by_cd
	 * @param lastUpdatedByCd  the value for ur_user.last_updated_by_cd
	 * @mbg.generated  Fri Sep 29 10:14:24 CST 2017
	 */
	public void setLastUpdatedByCd(String lastUpdatedByCd) {
		this.lastUpdatedByCd = lastUpdatedByCd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ur_user.deleted_flag
	 * @return  the value of ur_user.deleted_flag
	 * @mbg.generated  Fri Sep 29 10:14:24 CST 2017
	 */
	public Boolean getDeletedFlag() {
		return deletedFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ur_user.deleted_flag
	 * @param deletedFlag  the value for ur_user.deleted_flag
	 * @mbg.generated  Fri Sep 29 10:14:24 CST 2017
	 */
	public void setDeletedFlag(Boolean deletedFlag) {
		this.deletedFlag = deletedFlag;
	}
}