spring:
  datasource:
    name: manage
    url: jdbc:mysql://localhost:3306/manage?useSSL=false&zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
  data:
    mongodb:
      host: localhost
      port: 27017
      username: liyang
      password: liyang
      database: cust
  #solr:
    #custURL: http://localhost:8080/solr/cust
  redis:
    host: localhost
    port: 6379
    database: 1
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    status-page-url-path: /swagger-ui.html
mybatis:
  type-aliases-package: com.wcg.caoxian.bes.model
  mapper-locations:
    - classpath:/mappers/*.xml
