package com.wcg.caoxian.cust.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.wcg.caoxian.cust.model.Customer;
import com.wcg.caoxian.cust.vo.CustomerInputParamVo;
import com.wcg.caoxian.cust.vo.CustomerOutParamVo;
import com.wcg.caoxian.sdk.bean.PageBean;

public interface CustomerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cu_customer
     *
     * @mbg.generated Fri Sep 08 11:04:21 CST 2017
     */
    int deleteByPrimaryKey(String code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cu_customer
     *
     * @mbg.generated Fri Sep 08 11:04:21 CST 2017
     */
    int insert(Customer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cu_customer
     *
     * @mbg.generated Fri Sep 08 11:04:21 CST 2017
     */
    int insertSelective(Customer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cu_customer
     *
     * @mbg.generated Fri Sep 08 11:04:21 CST 2017
     */
    Customer selectByPrimaryKey(String code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cu_customer
     *
     * @mbg.generated Fri Sep 08 11:04:21 CST 2017
     */
    int updateByPrimaryKeySelective(Customer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cu_customer
     *
     * @mbg.generated Fri Sep 08 11:04:21 CST 2017
     */
    int updateByPrimaryKey(Customer record);
    
    /**
     * @Title: searchByCondition
     * @Description: CUST0020-根据查询条件获取客户信息列表
     * @author 李洋  liyang
     * @data 2017年9月8日 上午11:05:43
     * @return List<Customer>
     */
    List<CustomerOutParamVo> searchByCondition(@Param("customer")CustomerInputParamVo customerInputParamVo, @Param("pageBean")PageBean pageBean);

    /**
     * @Title: searchCount
     * @Description: CUST0020-根据查询条件获取客户信息记录数
     * @author 李洋  liyang
     * @data 2017年9月8日 上午11:05:29
     * @return Long
     */
	Long searchCount(CustomerInputParamVo customerInputParamVo);

	/**
	 * @Title: deleteCustomer
	 * @Description: CUST0040-客户信息删除
	 * @author 李洋  liyang
	 * @data 2017年9月18日 下午3:15:07
	 * @return int
	 */
	int deleteCustomer(String code);

	/**
	 * @Title: searchOneCust
	 * @Description: CUST0050-客户单记录查询
	 * @author 李洋  liyang
	 * @data 2017年9月19日 上午11:03:23
	 * @return CustomerOutParamVo
	 */
	CustomerOutParamVo searchOneCust(String code);
}