package com.wcg.caoxian.master.model;

import java.util.Date;

public class Master {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_master.code
     *
     * @mbg.generated Thu Aug 31 17:08:16 CST 2017
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_master.object_cd
     *
     * @mbg.generated Thu Aug 31 17:08:16 CST 2017
     */
    private String objectCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_master.name
     *
     * @mbg.generated Thu Aug 31 17:08:16 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_master.des
     *
     * @mbg.generated Thu Aug 31 17:08:16 CST 2017
     */
    private String des;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_master.spell_no
     *
     * @mbg.generated Thu Aug 31 17:08:16 CST 2017
     */
    private String spellNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_master.wubi_no
     *
     * @mbg.generated Thu Aug 31 17:08:16 CST 2017
     */
    private String wubiNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_master.sort_no
     *
     * @mbg.generated Thu Aug 31 17:08:16 CST 2017
     */
    private String sortNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_master.version_no
     *
     * @mbg.generated Thu Aug 31 17:08:16 CST 2017
     */
    private Integer versionNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_master.created_time
     *
     * @mbg.generated Thu Aug 31 17:08:16 CST 2017
     */
    private Date createdTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_master.created_by_cd
     *
     * @mbg.generated Thu Aug 31 17:08:16 CST 2017
     */
    private String createdByCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_master.last_updated_time
     *
     * @mbg.generated Thu Aug 31 17:08:16 CST 2017
     */
    private Date lastUpdatedTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_master.last_updated_by_cd
     *
     * @mbg.generated Thu Aug 31 17:08:16 CST 2017
     */
    private String lastUpdatedByCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_master.deleted_flag
     *
     * @mbg.generated Thu Aug 31 17:08:16 CST 2017
     */
    private Boolean deletedFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mst_master.code
     *
     * @return the value of mst_master.code
     *
     * @mbg.generated Thu Aug 31 17:08:16 CST 2017
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mst_master.code
     *
     * @param code the value for mst_master.code
     *
     * @mbg.generated Thu Aug 31 17:08:16 CST 2017
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mst_master.object_cd
     *
     * @return the value of mst_master.object_cd
     *
     * @mbg.generated Thu Aug 31 17:08:16 CST 2017
     */
    public String getObjectCd() {
        return objectCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mst_master.object_cd
     *
     * @param objectCd the value for mst_master.object_cd
     *
     * @mbg.generated Thu Aug 31 17:08:16 CST 2017
     */
    public void setObjectCd(String objectCd) {
        this.objectCd = objectCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mst_master.name
     *
     * @return the value of mst_master.name
     *
     * @mbg.generated Thu Aug 31 17:08:16 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mst_master.name
     *
     * @param name the value for mst_master.name
     *
     * @mbg.generated Thu Aug 31 17:08:16 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mst_master.des
     *
     * @return the value of mst_master.des
     *
     * @mbg.generated Thu Aug 31 17:08:16 CST 2017
     */
    public String getDes() {
        return des;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mst_master.des
     *
     * @param des the value for mst_master.des
     *
     * @mbg.generated Thu Aug 31 17:08:16 CST 2017
     */
    public void setDes(String des) {
        this.des = des;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mst_master.spell_no
     *
     * @return the value of mst_master.spell_no
     *
     * @mbg.generated Thu Aug 31 17:08:16 CST 2017
     */
    public String getSpellNo() {
        return spellNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mst_master.spell_no
     *
     * @param spellNo the value for mst_master.spell_no
     *
     * @mbg.generated Thu Aug 31 17:08:16 CST 2017
     */
    public void setSpellNo(String spellNo) {
        this.spellNo = spellNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mst_master.wubi_no
     *
     * @return the value of mst_master.wubi_no
     *
     * @mbg.generated Thu Aug 31 17:08:16 CST 2017
     */
    public String getWubiNo() {
        return wubiNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mst_master.wubi_no
     *
     * @param wubiNo the value for mst_master.wubi_no
     *
     * @mbg.generated Thu Aug 31 17:08:16 CST 2017
     */
    public void setWubiNo(String wubiNo) {
        this.wubiNo = wubiNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mst_master.sort_no
     *
     * @return the value of mst_master.sort_no
     *
     * @mbg.generated Thu Aug 31 17:08:16 CST 2017
     */
    public String getSortNo() {
        return sortNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mst_master.sort_no
     *
     * @param sortNo the value for mst_master.sort_no
     *
     * @mbg.generated Thu Aug 31 17:08:16 CST 2017
     */
    public void setSortNo(String sortNo) {
        this.sortNo = sortNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mst_master.version_no
     *
     * @return the value of mst_master.version_no
     *
     * @mbg.generated Thu Aug 31 17:08:16 CST 2017
     */
    public Integer getVersionNo() {
        return versionNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mst_master.version_no
     *
     * @param versionNo the value for mst_master.version_no
     *
     * @mbg.generated Thu Aug 31 17:08:16 CST 2017
     */
    public void setVersionNo(Integer versionNo) {
        this.versionNo = versionNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mst_master.created_time
     *
     * @return the value of mst_master.created_time
     *
     * @mbg.generated Thu Aug 31 17:08:16 CST 2017
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mst_master.created_time
     *
     * @param createdTime the value for mst_master.created_time
     *
     * @mbg.generated Thu Aug 31 17:08:16 CST 2017
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mst_master.created_by_cd
     *
     * @return the value of mst_master.created_by_cd
     *
     * @mbg.generated Thu Aug 31 17:08:16 CST 2017
     */
    public String getCreatedByCd() {
        return createdByCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mst_master.created_by_cd
     *
     * @param createdByCd the value for mst_master.created_by_cd
     *
     * @mbg.generated Thu Aug 31 17:08:16 CST 2017
     */
    public void setCreatedByCd(String createdByCd) {
        this.createdByCd = createdByCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mst_master.last_updated_time
     *
     * @return the value of mst_master.last_updated_time
     *
     * @mbg.generated Thu Aug 31 17:08:16 CST 2017
     */
    public Date getLastUpdatedTime() {
        return lastUpdatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mst_master.last_updated_time
     *
     * @param lastUpdatedTime the value for mst_master.last_updated_time
     *
     * @mbg.generated Thu Aug 31 17:08:16 CST 2017
     */
    public void setLastUpdatedTime(Date lastUpdatedTime) {
        this.lastUpdatedTime = lastUpdatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mst_master.last_updated_by_cd
     *
     * @return the value of mst_master.last_updated_by_cd
     *
     * @mbg.generated Thu Aug 31 17:08:16 CST 2017
     */
    public String getLastUpdatedByCd() {
        return lastUpdatedByCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mst_master.last_updated_by_cd
     *
     * @param lastUpdatedByCd the value for mst_master.last_updated_by_cd
     *
     * @mbg.generated Thu Aug 31 17:08:16 CST 2017
     */
    public void setLastUpdatedByCd(String lastUpdatedByCd) {
        this.lastUpdatedByCd = lastUpdatedByCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mst_master.deleted_flag
     *
     * @return the value of mst_master.deleted_flag
     *
     * @mbg.generated Thu Aug 31 17:08:16 CST 2017
     */
    public Boolean getDeletedFlag() {
        return deletedFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mst_master.deleted_flag
     *
     * @param deletedFlag the value for mst_master.deleted_flag
     *
     * @mbg.generated Thu Aug 31 17:08:16 CST 2017
     */
    public void setDeletedFlag(Boolean deletedFlag) {
        this.deletedFlag = deletedFlag;
    }
}