package com.wcg.caoxian.user.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.wcg.caoxian.sdk.bean.PageBean;
import com.wcg.caoxian.user.model.Role;
import com.wcg.caoxian.user.vo.RoleSearchOutParamVo;
import com.wcg.caoxian.user.vo.RoleReAndUpVo;

public interface RoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ur_role
     *
     * @mbg.generated Fri Sep 22 13:40:32 CST 2017
     */
    int deleteByPrimaryKey(String code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ur_role
     *
     * @mbg.generated Fri Sep 22 13:40:32 CST 2017
     */
    int insert(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ur_role
     *
     * @mbg.generated Fri Sep 22 13:40:32 CST 2017
     */
    int insertSelective(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ur_role
     *
     * @mbg.generated Fri Sep 22 13:40:32 CST 2017
     */
    Role selectByPrimaryKey(String code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ur_role
     *
     * @mbg.generated Fri Sep 22 13:40:32 CST 2017
     */
    int updateByPrimaryKeySelective(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ur_role
     *
     * @mbg.generated Fri Sep 22 13:40:32 CST 2017
     */
    int updateByPrimaryKey(Role record);

    /**
     * @Title: searchNameCount
     * @Description: 校验名称是否存在
     * @author 李洋  liyang
     * @data 2017年10月10日 下午5:38:19
     * @return int
     */
	int searchNameCount(RoleReAndUpVo roleVo);

	/**
	 * @Title: getByCode
	 * @Description: USER0180-角色单记录查询
	 * @author 李洋  liyang
	 * @data 2017年10月11日 上午10:37:34
	 * @return RoleSearchOutParamVo
	 */
	RoleSearchOutParamVo getByCode(String code);

	/**
	 * @Title: deleteByCode
	 * @Description: USER0190-角色删除
	 * @author 李洋  liyang
	 * @data 2017年10月11日 下午1:39:29
	 * @return int
	 */
	int deleteByCode(String code);

	/**
	 * @Title: searchByCondition
	 * @Description: USER0200-角色列表查询
	 * @author 李洋  liyang
	 * @data 2017年10月11日 下午1:50:49
	 * @return List<RoleSearchOutParamVo>
	 */
	List<RoleSearchOutParamVo> searchByCondition(@Param("name")String name, @Param("pageBean")PageBean pageBean);

	/**
	 * @Title: searchCount
	 * @Description: USER0200-角色列表查    记录数
	 * @author 李洋  liyang
	 * @data 2017年10月11日 下午1:53:40
	 * @return int
	 */
	Long searchCount(@Param("name")String name);
}