package com.wcg.caoxian.cust.model;

import java.util.Date;

public class Customer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_customer.code
     *
     * @mbg.generated Fri Sep 08 11:04:21 CST 2017
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_customer.type_cd
     *
     * @mbg.generated Fri Sep 08 11:04:21 CST 2017
     */
    private String typeCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_customer.name
     *
     * @mbg.generated Fri Sep 08 11:04:21 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_customer.sex_cd
     *
     * @mbg.generated Fri Sep 08 11:04:21 CST 2017
     */
    private String sexCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_customer.married_cd
     *
     * @mbg.generated Fri Sep 08 11:04:21 CST 2017
     */
    private String marriedCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_customer.certification_type_cd
     *
     * @mbg.generated Fri Sep 08 11:04:21 CST 2017
     */
    private String certificationTypeCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_customer.certification_no
     *
     * @mbg.generated Fri Sep 08 11:04:21 CST 2017
     */
    private String certificationNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_customer.birthday
     *
     * @mbg.generated Fri Sep 08 11:04:21 CST 2017
     */
    private Date birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_customer.email
     *
     * @mbg.generated Fri Sep 08 11:04:21 CST 2017
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_customer.mobile
     *
     * @mbg.generated Fri Sep 08 11:04:21 CST 2017
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_customer.created_time
     *
     * @mbg.generated Fri Sep 08 11:04:21 CST 2017
     */
    private Date createdTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_customer.created_by_cd
     *
     * @mbg.generated Fri Sep 08 11:04:21 CST 2017
     */
    private String createdByCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_customer.last_updated_time
     *
     * @mbg.generated Fri Sep 08 11:04:21 CST 2017
     */
    private Date lastUpdatedTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_customer.last_updated_by_cd
     *
     * @mbg.generated Fri Sep 08 11:04:21 CST 2017
     */
    private String lastUpdatedByCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_customer.deleted_flag
     *
     * @mbg.generated Fri Sep 08 11:04:21 CST 2017
     */
    private Boolean deletedFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_customer.code
     *
     * @return the value of cu_customer.code
     *
     * @mbg.generated Fri Sep 08 11:04:21 CST 2017
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_customer.code
     *
     * @param code the value for cu_customer.code
     *
     * @mbg.generated Fri Sep 08 11:04:21 CST 2017
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_customer.type_cd
     *
     * @return the value of cu_customer.type_cd
     *
     * @mbg.generated Fri Sep 08 11:04:21 CST 2017
     */
    public String getTypeCd() {
        return typeCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_customer.type_cd
     *
     * @param typeCd the value for cu_customer.type_cd
     *
     * @mbg.generated Fri Sep 08 11:04:21 CST 2017
     */
    public void setTypeCd(String typeCd) {
        this.typeCd = typeCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_customer.name
     *
     * @return the value of cu_customer.name
     *
     * @mbg.generated Fri Sep 08 11:04:21 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_customer.name
     *
     * @param name the value for cu_customer.name
     *
     * @mbg.generated Fri Sep 08 11:04:21 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_customer.sex_cd
     *
     * @return the value of cu_customer.sex_cd
     *
     * @mbg.generated Fri Sep 08 11:04:21 CST 2017
     */
    public String getSexCd() {
        return sexCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_customer.sex_cd
     *
     * @param sexCd the value for cu_customer.sex_cd
     *
     * @mbg.generated Fri Sep 08 11:04:21 CST 2017
     */
    public void setSexCd(String sexCd) {
        this.sexCd = sexCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_customer.married_cd
     *
     * @return the value of cu_customer.married_cd
     *
     * @mbg.generated Fri Sep 08 11:04:21 CST 2017
     */
    public String getMarriedCd() {
        return marriedCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_customer.married_cd
     *
     * @param marriedCd the value for cu_customer.married_cd
     *
     * @mbg.generated Fri Sep 08 11:04:21 CST 2017
     */
    public void setMarriedCd(String marriedCd) {
        this.marriedCd = marriedCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_customer.certification_type_cd
     *
     * @return the value of cu_customer.certification_type_cd
     *
     * @mbg.generated Fri Sep 08 11:04:21 CST 2017
     */
    public String getCertificationTypeCd() {
        return certificationTypeCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_customer.certification_type_cd
     *
     * @param certificationTypeCd the value for cu_customer.certification_type_cd
     *
     * @mbg.generated Fri Sep 08 11:04:21 CST 2017
     */
    public void setCertificationTypeCd(String certificationTypeCd) {
        this.certificationTypeCd = certificationTypeCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_customer.certification_no
     *
     * @return the value of cu_customer.certification_no
     *
     * @mbg.generated Fri Sep 08 11:04:21 CST 2017
     */
    public String getCertificationNo() {
        return certificationNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_customer.certification_no
     *
     * @param certificationNo the value for cu_customer.certification_no
     *
     * @mbg.generated Fri Sep 08 11:04:21 CST 2017
     */
    public void setCertificationNo(String certificationNo) {
        this.certificationNo = certificationNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_customer.birthday
     *
     * @return the value of cu_customer.birthday
     *
     * @mbg.generated Fri Sep 08 11:04:21 CST 2017
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_customer.birthday
     *
     * @param birthday the value for cu_customer.birthday
     *
     * @mbg.generated Fri Sep 08 11:04:21 CST 2017
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_customer.email
     *
     * @return the value of cu_customer.email
     *
     * @mbg.generated Fri Sep 08 11:04:21 CST 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_customer.email
     *
     * @param email the value for cu_customer.email
     *
     * @mbg.generated Fri Sep 08 11:04:21 CST 2017
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_customer.mobile
     *
     * @return the value of cu_customer.mobile
     *
     * @mbg.generated Fri Sep 08 11:04:21 CST 2017
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_customer.mobile
     *
     * @param mobile the value for cu_customer.mobile
     *
     * @mbg.generated Fri Sep 08 11:04:21 CST 2017
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_customer.created_time
     *
     * @return the value of cu_customer.created_time
     *
     * @mbg.generated Fri Sep 08 11:04:21 CST 2017
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_customer.created_time
     *
     * @param createdTime the value for cu_customer.created_time
     *
     * @mbg.generated Fri Sep 08 11:04:21 CST 2017
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_customer.created_by_cd
     *
     * @return the value of cu_customer.created_by_cd
     *
     * @mbg.generated Fri Sep 08 11:04:21 CST 2017
     */
    public String getCreatedByCd() {
        return createdByCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_customer.created_by_cd
     *
     * @param createdByCd the value for cu_customer.created_by_cd
     *
     * @mbg.generated Fri Sep 08 11:04:21 CST 2017
     */
    public void setCreatedByCd(String createdByCd) {
        this.createdByCd = createdByCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_customer.last_updated_time
     *
     * @return the value of cu_customer.last_updated_time
     *
     * @mbg.generated Fri Sep 08 11:04:21 CST 2017
     */
    public Date getLastUpdatedTime() {
        return lastUpdatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_customer.last_updated_time
     *
     * @param lastUpdatedTime the value for cu_customer.last_updated_time
     *
     * @mbg.generated Fri Sep 08 11:04:21 CST 2017
     */
    public void setLastUpdatedTime(Date lastUpdatedTime) {
        this.lastUpdatedTime = lastUpdatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_customer.last_updated_by_cd
     *
     * @return the value of cu_customer.last_updated_by_cd
     *
     * @mbg.generated Fri Sep 08 11:04:21 CST 2017
     */
    public String getLastUpdatedByCd() {
        return lastUpdatedByCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_customer.last_updated_by_cd
     *
     * @param lastUpdatedByCd the value for cu_customer.last_updated_by_cd
     *
     * @mbg.generated Fri Sep 08 11:04:21 CST 2017
     */
    public void setLastUpdatedByCd(String lastUpdatedByCd) {
        this.lastUpdatedByCd = lastUpdatedByCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_customer.deleted_flag
     *
     * @return the value of cu_customer.deleted_flag
     *
     * @mbg.generated Fri Sep 08 11:04:21 CST 2017
     */
    public Boolean getDeletedFlag() {
        return deletedFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_customer.deleted_flag
     *
     * @param deletedFlag the value for cu_customer.deleted_flag
     *
     * @mbg.generated Fri Sep 08 11:04:21 CST 2017
     */
    public void setDeletedFlag(Boolean deletedFlag) {
        this.deletedFlag = deletedFlag;
    }
}