server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        svn:
          uri: https://localhost:9090/svn/MyItems/config
          username: admin
          password: admin
      enabled: true
  profiles:
    active: subversion
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    status-page-url: /info.html