server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github:com/liyang-tech/springcloud-demo/config
          username: liyang-tech
          password: YANG2fei1314
